### ISSUE TITLE
Create dedicated documentation for typelevel-site-plugin

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#186]
With much thanks to @quafadas for guinea-pigging this, with a not-so-great experience.

Currently, the documentation consists of a brief FAQ and some bullet points on the customization page. In fact, this plugin probably deserves a page of its own.

The other important thing is that non-TL projects will want to configure the plugin differently than TL projects in order to override the default TL Laika theme. It seems the right thing to do is point them directly to the Laika docs and tell them which typelevel-specific settings to ignore.

It's also probably worth pointing out that this is an optional and opinionated plugin that bakes in Laika. Projects that don't want Laika and/or want to do very custom things should probably explore other microsite solutions instead of attempting to retrofit this plugin.

**Comment by Quafadas** [comment]
I've been trying to think about what made this tricky, and is specific to this plugin, rather than my project. 

It is worth noting that I came in as a complete n00b... so some challenges were to be expected. Getting a n00b publishing to maven / own site as fast as I go there is impressive. So let's not forget that. 

Artefact publishing worked startlingly smoothly - it was a killer feature which kept me going through some docs troubles.

Publishing the doc website, and even Laika itself worked really well, _once I got it working_. 

I think that shows that the convenience this plugin targets, is actually not that far off. And is a super attractive goal. 

I did hit a couple of issues. Many may be idiosyncratic to my library which deliberately tries to cross the JS / JVM boundaries, which is in general a mess and bad idea :-), let's not write about there here. None-the-less, my suggestions: 

One
I followed the docs on the Laika website, but it didn't have the effects advertised. It was not obvious to me that tlXXX settings, suggested by Arman, and the Laika SBT plugin settings advertised in Laika docs, would trample each other. Some of the behaviour become seemingly non-deterministic ( I suspect because depending on the position of settings in build.sbt then changed it's behaviour), when changing things, this was difficult. 

It's not obvious to me (outside of reading the plugin code) how I could have found which settings interact and trample each other. Hence, for a non-TL user (who very likely wants to customise the colors / other settings), I would propose to try to find a way to make it possible to follow the Laika documentation for the SBT plugin directly, rather than use the TLHelium mechanisms. Ideally perhaps, somehow enforce "one paradigm or the other but not both" if that is possible.

Two
The FAQs suggesting running docs/laikaPreview
https://typelevel.org/sbt-typelevel/faq.html

In my case, I had pre-existing markdown / documentation (I had JSON in the markdown) which was not compatible with Laikas parsing engine (I believe). laikaPreview actually hid the exceptions it generated from me. It took me some hours, to realise that actually, the edit loop should be instantaneous, when working correctly. I had to figure out the undlerlying commands (e.g. tlSite) myself, some of which did eventually hint that Laika was choking in a sea of exceptions, rather than working nominally. 

In this case, I think I would recommend documenting the _expectation_ of the local edit lop. i.e. what success looks like. A naive user should be able to observe the delta to that vs their experience. Perhaps a GIF in the docs? And perhaps a starting point for investigating (the commands that sit underneath laikaPreview?) Had I realised that a 60 second start time was not expected, I think I would have started digging in the right place, much faster. I suspect I accepted too much pain because I didn't understand what the target state was. 

The attractiveness of having a single command to compile / start the doc server makes a lot of sense (docs/laikaPreview). I think it is the right aim for a n00b... so fundamentally, I think the process suggested by the FAQ is the right starting point. 

I hope that feedback helps, and you think is sensible.

**Comment by armanbilge** [comment]
@Quafadas thank you very much for this valuable feedback!

> I think that shows that the convenience this plugin targets, is actually not that far off. And is a super attractive goal.

❤️ 

> Hence, for a non-TL user (who very likely wants to customise the colors / other settings), I would propose to try to find a way to make it possible to follow the Laika documentation for the SBT plugin directly, rather than use the TLHelium mechanisms.

This is exactly how it should work right now: you should be able to completely configure your site following the Laika documentation, without using any `tlXXX` settings. @Quafadas would you mind trying this? If it doesn't work, that's a bug that we should definitely fix.

> It was not obvious to me that tlXXX settings, suggested by Arman, and the Laika SBT plugin settings advertised in Laika docs, would trample each other.

This was a "documentation" bug: you were doing things right before, following the Laika manual, and I gave you bad suggestions to use `tlXXX` settings. This was my fault, and it made things very confusing. I'm sorry about that.

> laikaPreview actually hid the exceptions it generated from me.

This sounds like a bug in Laika itself. Would you mind opening an issue about it there? :)
https://github.com/planet42/laika

> The attractiveness of having a single command to compile / start the doc server makes a lot of sense (docs/laikaPreview)

Yes, unfortunately we don't really have that right now :( the problem is, there are two steps: the mdoc step and the laika step. So even if the laika step is on local edit loop, it won't reflect changes to your mdoc. mdoc also has its own edit loop, but then you can't preview it in laika. It doesn't seem easy to get sbt to run both of these loops at the same time. This is actually a really important thing to fix.

**Comment by Quafadas** [comment]
> Yes, unfortunately we don't really have that right now :( the problem is, there are two steps: the mdoc step and the laika step. So even if the laika step is on local edit loop, it won't reflect changes to your mdoc. mdoc also has its own edit loop, but then you can't preview it in laika. It doesn't seem easy to get sbt to run both of these loops at the same time. This is actually a really important thing to fix.

Yes, I think I see this. Am I correct though, that it would be relatively easy to "fix" in documentation, by having two terminals, one with each command? That's where I ended up. I was happy with that solution.

**Comment by armanbilge** [comment]
> Am I correct though, that it would be relatively easy to "fix" in documentation, by having two terminals, one with each command? That's where I ended up. I was happy with that solution.

Oh, nice, if it worked well for you that sounds like a good workaround! 👍 would appreciate a PR updated the docs.

**Comment by armanbilge** [comment]
I merged a bunch of site-related PRs and now the current docs for it are rather stale. So all the settings/tasks should be refreshed as well while working on this.
