### ISSUE TITLE
typelevel.g8

### ISSUE THREAD

**Issue by armanbilge** [typelevel/sbt-typelevel#37]
Spinning out of https://github.com/typelevel/sbt-typelevel/issues/16#issuecomment-1003135292.

**Comment by armanbilge** [comment]
Here's an example g8 template: https://github.com/davenverse/library.g8

**Comment by armanbilge** [comment]
Another random Discord discussion suggests considering a vanilla GitHub template as an alternative. Actually, I like the template idea.

**Comment by rossabaker** [comment]
A g8 template fills in parameters and is sets up a package-aware file structure.  GitHub templates were so lacking in my Haskell days, some people were willing to install a JVM just to get g8.  g8 is one of Scala's best features!

**Comment by valencik** [comment]
Ok, an initial attempt is up: https://github.com/valencik/proto-typelevel.g8
You can try it with: `sbt new valencik/proto-typelevel.g8`

Included:
- basic IOApp and test using munit-cats-effect
- only sbt-typelevel for sbt plugins
- CODE_OF_CONDUCT.md
- minimal .scalafmt.conf
- .gitignore

Soon to be included:
- github workflow files
- README.md

To go much further I think we need to answer some questions about goals and use case.
I think we should optimize for new library creation and providing an example of current best practices.
Additionally, I think it's easier to delete/remove things you don't want instead of adding them.
So we can perhaps include extras as long as they don't over complicate things and they are commonly used.
Along that front I think it would be worthwhile to add the following:

- example usage of mdoc
- example usage of the site generation
- license headers
- scalafix set to organize imports

Let me know if any of those strike you as too much.

**Comment by armanbilge** [comment]
Thanks for all your work on this. 

> Additionally, I think it's easier to delete/remove things you don't want instead of adding them.

That's a good point. I think so too.

> example usage of mdoc
> example usage of the site generation

👍 yep these go hand-in-hand :)

> license headers

Woops, actually sbt-typelevel enforces these anyway! So we should add them :)

> scalafix set to organize imports

I'm interested if there's a convenient way we can upstream this configuration into sbt-typelevel itself.

**Comment by rossabaker** [comment]
I gave this a try at https://github.com/http4s/module.g8/tree/proto-http4s.  Looking good!  I'll upstream anything that isn't an http4sification.

**Comment by armanbilge** [comment]
Now we just need to update the site! :)
