### ISSUE TITLE
Configurable ignored modules on dependency submission

### ISSUE THREAD

**Issue by rossabaker** [typelevel/sbt-typelevel#442]
Any Scala 3 build using dependency submission will get 14 useless Dependabot alerts due to stale scaladoc dependencies.  I propose a key to ignore a set of modules, to render as the `modules-ignore` parameter in the GitHub Action.  

I already baked this into the plugin at $WORK and can port it here if there's interest, once I confirm that it works.

**Comment by armanbilge** [comment]
I noticed we've been getting a lot of [build-related Dependabot alerts in Cats Effect](https://github.com/typelevel/cats-effect/security/dependabot?q=) as well.

So this seems like a good idea, and maybe we can put in some sensible defaults. For example instead of `modules-ignore` I wonder if we can `config-ignore` the `test`, `scala-tool`, and `scala-doc-tool` configs. Also, maybe no-publish projects can automatically register themselves with `modules-ignore`.

**Comment by rossabaker** [comment]
Our internal plugin sets a default `config-ignore` (we don't do test, but I like it) to such good effect that consumers don't typically need to configure anything else.  But I like your no-publish idea, too.

**Comment by rossabaker** [comment]
Maybe also `doc`?  mdoc has a stale pdf-box that's a few dependencies deep.  I think it would have about the same pros and cons as ignoring `test`.

**Comment by armanbilge** [comment]
Does `mdoc` fall under `doc`? I thought it might fall under no-publish but I have no idea 🤔

**Comment by rossabaker** [comment]
Oh, I don't think `doc` is right.  The configuration is called `docs`, and it doesn't have a classpath.  mdoc and its insecure great-great-great grandchild shows up in `doc / Compile`.  The no-publish rule would do what we want here.
