### ISSUE TITLE
Remove `sbt-dependency-graph`

### ISSUE THREAD

**Issue by jedesah** [typelevel/sbt-typelevel#7]
That's more of a developer tool that should be installed by developers themselves if they find it useful. I wouldn't mind or mention anything if it wasn't for the fact that its presence in `sbt-typelevel` is interfering with my own (more recent) installation of the `sbt-dependency-graph` in my global sbt settings.

**Comment by larsrh** [comment]
The problem is that I need `sbt-dependency-graph` for the dependency conflict check. I think in the grand scheme of things I should remove `sbt-typelevel` from downstream projects, since many of its features are either in SBT, trivial to do, or subsumed by [https://github.com/InTheNow/sbt-catalysts](sbt-catalysts).

**Comment by larsrh** [comment]
I have now haphazardly updated `sbt-dependency-graph` and will cut a fresh release.
