### ISSUE TITLE
sbt-typelevel-versioning PVP support.

### ISSUE THREAD

**Issue by zarthross** [typelevel/sbt-typelevel#708]
Is there any interest in entertaining changes to the sbt-typelevel-versioning plugin to support PVP?  

I want to be able to use this plugin for some projects, but also would love to use PVP for the versioning instead of semver.  

I'm happy to do any work and submit a PR for it, but before doing so I wanted to make sure it would be well received first, otherwise I'll just fork the plugin and do what I need to do.

**Comment by satorg** [comment]
Sorry for my ignorance, what is PVP?

**Comment by zarthross** [comment]
PVP is an alternative Version Scheme, its supported by SBT
https://www.scala-sbt.org/1.x/docs/Publishing.html#Version+scheme

Here is a full descriptor: https://pvp.haskell.org/

**Comment by armanbilge** [comment]
> Is there any interest in entertaining changes to the sbt-typelevel-versioning plugin to support PVP?

Sorry, not particularly. sbt-typelevel is intended to be opinionated on best practices, and early-semver based versioning seems to be the current best practice in the Scala community that is used by all major projects including the compiler itself. So I am genuinely curious: is there a reason that you prefer to use PVP?

---

Separately, I don't think you need to fork sbt-typelevel to make the changes you want. You can either create your own "plugin cocktail" that omits the sbt-typelelevel-mima plugin.

Or you could just override this setting in your build, or you own plugin.
https://github.com/typelevel/sbt-typelevel/blob/8c204839721b80875bd85793b4e18c42645edff1/mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala#L45-L48

**Comment by isomarcte** [comment]
> is there a reason that you prefer to use PVP?

PVP does solve a few problems that can't be expressed in early-semver/semver. It is fundamentally just slightly more expressive. Now, the question would be how often do you need that expressiveness, the answer of course is that it depends.

I did a more full write up on the reasons behind it years ago here: https://github.com/isomarcte/sbt-version-scheme-enforcer?tab=readme-ov-file#why-does-this-plugin-exist

My personal opinion on this in Scala is that with sufficiently good tooling, projects shouldn't care what version scheme other projects are using, because really we don't, right? We care about the bin-compat and the ability to express and understand that. We are fortunate enough to have relatively good tooling to detect binary breaking changes, both in a project and in our dependencies, and express/verify the intended binary compatibility of a given revision of a project.

FWIW though, I do get that `sbt-typelvel`'s utility partially comes from it being very opinionated. And I also get that in general semver is just better understood, which _does have some utility, in and of itself_.

>  including the compiler itself

Is that actually true though? `2.12.x` compiled code is _not_ compatible with `2.13.x`, right? That would be PVP, neither early-semver nor semver.

**Comment by zarthross** [comment]
> So I am genuinely curious: is there a reason that you prefer to use PVP?

My team uses it help express the difference between a binary incompat change that is minor (a few function definition changes), vs a very large change like CE2 to CE3 was.  This allows us to internally tell at a glance how much work it is to move to the new from the old library.

I will admit this is largely personal preference.

_________________

 > Separately, I don't think you need to fork sbt-typelevel to make the changes you want. You can either create your own "plugin cocktail" that omits the sbt-typelelevel-mima plugin.

What we would fork would be just the version plugin.  I want the nice features for release that the version plugin supports, just with PVP instead of Semver.

**Comment by zarthross** [comment]
It's completely fine if there's not interest in widening the support for version schemes within this, i understand its supposed to be opinionated.  I felt I should ask first before I put in the work elsewhere.

**Comment by armanbilge** [comment]
> Is that actually true though?

I'm talking about Scala 3. Yes, Scala 2 was using a different version scheme (possibly PVP-like but I'm not certain). What I can say is that now that Scala 2.13 is dropping forward-compatibility, the lack of semver version scheme will sting.

> It is fundamentally just slightly more expressive.

I'm not sure I agree but I haven't had a chance to read your write-up. Looking at the complications with Scala 2.13 dropping forward compatibility, I would say it's less expressive.

> What we would fork would be just the version plugin.

That makes sense to me.

**Comment by zarthross** [comment]
> > It is fundamentally just slightly more expressive.
> 
> I'm not sure I agree but I haven't had a chance to read your write-up. Looking at the complications with Scala 2.13 dropping forward compatibility, I would say it's less expressive.

Tangent: Scala 2 could benefit from PVP exactly because it lost forward compatiblity.  You can say, `2.13.14.0` and `2.13.14.1` are compatible in both directions, but `2.13.15.0` is only backward compatible with `2.13.14.X` but not forward.
